# **AICP Internship Task Week 1**

In [ ]:
#Importing the Numpy library as 'np'
import numpy as np

## Creating an array of even integers from 30 to 70

In [ ]:
# We use np.arrange() with a step size of 2 to show only even integers
array = np.arange(30,71,2)

print('Array of all even intgers from 30 to 70 : ')

print(array)



Array of all even intgers from 30 to 70 : 
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Generating an array of 15 random numbers from a standrad normal distribution


In [ ]:
#We use np.random.normal() to generate an array of 15 random numbers from a standrad normal distribution

rand_num= np.random.normal(0,1,15)

print("An array of 15 random numbers from a standrad normal distribution is : ")
print(rand_num)


An array of 15 random numbers from a standrad normal distribution is : 
[-0.64855023 -1.76499966  0.14570591  1.95154887 -1.21723798 -0.80711495
 -0.37103518 -0.93954115 -0.44224419 -0.86891476 -0.2014137   0.83548192
  0.44997338  0.18606616  0.67888842]


## Computing cross product of two given vectors

In [ ]:
#We declare the two vectors
x=[1,2]
y=[3,4]

#Find cross product of two given vectors
result= np.cross(x,y)

print("Cross product of the two given vectors is:",result)

Cross product of the two given vectors is: -2


#Determinant of an array using NumPy

In [ ]:
# Define your array
arr = np.array([[1, 2],[3, 4]])

#numpy.linalg.det() function is a part of NumPy's linear algebra module
#This function is used to compute the determinant of a square matrix.


#Calculate the determinant of the matrix
determinant = np.linalg.det(arr)

print("Determinant of the array:")
print(determinant)


Determinant of the array:
-2.0000000000000004


# Creating 3x3x3 array with random values

In [ ]:
#Generating a 3x3 Numpy array 'x' filled with random floats between 0 and 1 using np.random.random()
x=np.random.random((3,3,3))

#printing the array 'x'
print(x)

[[[0.90575969 0.00496098 0.28432559]
  [0.3329402  0.25632252 0.46619556]
  [0.59438479 0.38810265 0.90130579]]

 [[0.08892591 0.6814387  0.46877625]
  [0.60772922 0.52071287 0.3860595 ]
  [0.48364086 0.6019215  0.85080924]]

 [[0.44652894 0.71577984 0.88639276]
  [0.69524093 0.60733039 0.36830692]
  [0.24073644 0.7991826  0.39632988]]]


 # Create a 5x5 array with random values and finding maximum and minimum values

In [ ]:
#Generating a 5x5 Numpy array 'x' filled with random floats between 0 and 1 using np.random.random()
x=np.random.random((5,5))

#printing the orginal array 'x'
print("Original array:")
print(x)

#calculating the minimum and maximum values in array 'x' using x.min() and x.max() functions
xmin, xmax = x.min() , x.max()

#Printing the minimum and maximum values of the array of 'x'
print('Minimum value:')
print(xmin)
print('Maximum value:')
print(xmax)


Original array:
[[0.34933687 0.82288338 0.74240505 0.9102357  0.23030995]
 [0.52863894 0.44455146 0.79005389 0.22245311 0.26882706]
 [0.1099597  0.59185225 0.16122738 0.4436193  0.6701006 ]
 [0.79964323 0.11031606 0.98471257 0.90433531 0.71235602]
 [0.54753632 0.20895845 0.87094864 0.44044049 0.43785294]]
Minimum value:
0.10995969855403187
Maximum value:
0.9847125709506582


# Compute the mean, standard deviation, and variance of a given array

In [ ]:
# Define your array
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

# Compute the mean along the second axis
mean_values = np.mean(arr, axis=1)

# Compute the standard deviation along the second axis
std_deviation = np.std(arr, axis=1)

# Compute the variance along the second axis
variance = np.var(arr, axis=1)

print("Mean along the second axis:")
print(mean_values)

print("\nStandard deviation along the second axis:")
print(std_deviation)

print("\nVariance along the second axis:")
print(variance)


Mean along the second axis:
[2. 5. 8.]

Standard deviation along the second axis:
[0.81649658 0.81649658 0.81649658]

Variance along the second axis:
[0.66666667 0.66666667 0.66666667]
